// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: usermgmt/usermgmt.proto

package usermgmtGRPC

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserManagment_CreatNewUser_FullMethodName = "/usermgmt.UserManagment/CreatNewUser"
)

// UserManagmentClient is the client API for UserManagment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserManagmentClient interface {
	CreatNewUser(ctx context.Context, in *NewUser, opts ...grpc.CallOption) (*User, error)
}

type userManagmentClient struct {
	cc grpc.ClientConnInterface
}

func NewUserManagmentClient(cc grpc.ClientConnInterface) UserManagmentClient {
	return &userManagmentClient{cc}
}

func (c *userManagmentClient) CreatNewUser(ctx context.Context, in *NewUser, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, UserManagment_CreatNewUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserManagmentServer is the server API for UserManagment service.
// All implementations must embed UnimplementedUserManagmentServer
// for forward compatibility.
type UserManagmentServer interface {
	CreatNewUser(context.Context, *NewUser) (*User, error)
	mustEmbedUnimplementedUserManagmentServer()
}

// UnimplementedUserManagmentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserManagmentServer struct{}

func (UnimplementedUserManagmentServer) CreatNewUser(context.Context, *NewUser) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatNewUser not implemented")
}
func (UnimplementedUserManagmentServer) mustEmbedUnimplementedUserManagmentServer() {}
func (UnimplementedUserManagmentServer) testEmbeddedByValue()                       {}

// UnsafeUserManagmentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserManagmentServer will
// result in compilation errors.
type UnsafeUserManagmentServer interface {
	mustEmbedUnimplementedUserManagmentServer()
}

func RegisterUserManagmentServer(s grpc.ServiceRegistrar, srv UserManagmentServer) {
	// If the following call pancis, it indicates UnimplementedUserManagmentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserManagment_ServiceDesc, srv)
}

func _UserManagment_CreatNewUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagmentServer).CreatNewUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserManagment_CreatNewUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagmentServer).CreatNewUser(ctx, req.(*NewUser))
	}
	return interceptor(ctx, in, info, handler)
}

// UserManagment_ServiceDesc is the grpc.ServiceDesc for UserManagment service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserManagment_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "usermgmt.UserManagment",
	HandlerType: (*UserManagmentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatNewUser",
			Handler:    _UserManagment_CreatNewUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "usermgmt/usermgmt.proto",
}
